parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint/eslint-plugin'
env:
  node: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 5
rules:
  no-unused-vars: off
  valid-jsdoc:
    - error
    - requireReturn: true
      requireReturnType: false
      requireParamType: false
      requireParamDescription: false
      requireReturnDescription: false
